### ISSUE TITLE
Objectdefinition problem

### ISSUE THREAD

**Issue by Kamikaze99** [instalator/ioBroker.mpd#13]
hello,
i installed mpd version1.0.0 on my iobroker installation. If i check the object definition then i found some difficult definitions:
setvol: is logical, i mean it should be number, because i will set the volume to 80
playid: is logical, but it should be number for song number
albumartist: Ist Logikwert, but it should be string to define the artist of the album
clear: is string, should be logical to clear the playlist
file: is logical but should be string to define URL
...
Can you check it and let me known if it´s an adapter problem or make i a mistake?

Many Thanks

**Comment by instalator** [comment]
> setvol: is logical, i mean it should be number, because i will set the volume to 80
https://github.com/instalator/ioBroker.mpd/blob/580354d4b07ccaf973793ee33fe914213ac5c9af/io-package.json#L1000

> playid: is logical, but it should be number for song number
https://github.com/instalator/ioBroker.mpd/blob/580354d4b07ccaf973793ee33fe914213ac5c9af/io-package.json#L1187

> albumartist: Ist Logikwert, but it should be string to define the artist of the album
added
> clear: is string, should be logical to clear the playlist
changed
> file: is logical but should be string to define URL
added

**Comment by Kamikaze99** [comment]
Hello, 

i have checked it.
clear: it looks good. i marked it with true and playlist ist empty.
albumartist: it looks good.
file: it looks good.
setvol: you are right, that the definition in your file is correct, but in iobroker it looks like 
`{
  "common": {
    "name": "Playback options setvol",
    "role": "media.setvol",
    "type": "boolean",
    "read": true,
    "write": true,
    "def": false
  },
  "native": {},
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1638
  },
  "_id": "mpd.0.setvol",
  "type": "state"
}`

playid: same as setvol
`{
  "common": {
    "name": "Controlling playback playid",
    "role": "media.playid",
    "type": "boolean",
    "read": true,
    "write": true,
    "def": false
  },
  "native": {},
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1638
  },
  "_id": "mpd.0.playid",
  "type": "state"
}`

i will check the other objects too, and let you known

**Comment by Kamikaze99** [comment]
Hello,
i have tried the complete analysis and will send you my results. I hope you understand my table and can give me your opinion.
If i understoodit correctly  i can change it in my iobroker.json file by myself, but after upgrade the adapter my modifications are lost.

Object					Type (my opion)		Type iob	Remarks
---------------------------------------------------------------
add: 					String				String		--> io.
addid:					String				String		--> io.
addplay:				String				String		--> io.	
addtagid:				String 				String		--> io.
album					String				String		--> io.
albumartist:			String				String		--> io.
albums					number				state		--> new definition necessary
artist					String				String		--> io.
artists:				number				state		--> new definition necessary
audio					String				State		--> new definition necessary
bitrate					number				Number		--> io.
clear					Logical				Logical		--> io.
cleartagid				String				String		--> io.
composer				String				State		--> new definition necessary
consume					Logical				State		--> new definition necessary
count					String				String		--> io.
crossfade				Number				Integer		--> io.
current_duration		Number				String		--> io.
current_duration_s		Number				Number		--> io.
current_elapsed			String				String		--> io.
date					Number or String	String		--> io.
db_playtime				Number				State		--> new definition necessary
db_update				Number				State		--> new definition necessary
delete					String				String		--> io.
deleteid				Number				String		--> io.
disableoutput			String				String		--> io.
disc					Number or String	State		--> new definition necessary
elapsed					Number				Number		--> io.
enableoutput			String				String		--> io.
error					String				State		--> new definition necessary
file					String				String		--> io.
find					String				String		--> io.
findadd					String				String		--> io.
genre					String				String		--> io.
id						Number				Number		--> io.	
last-modified			unknown				State		--> new definition necessary				
list					String				String		--> io.
listall					String				String		--> io.
listallinfo				String				String		--> io.
listfiles				String				String		--> io.
listmounts				String				String		--> io.
listneighbors			String				String		--> io.
listplaylist			String				String		--> io.
listplaylistinfo		String				String		--> io.
listplaylists			String				String		--> io.
load					string				String		--> io.
lsinfo					String				String		--> io.
mixrampdb				Number				State		--> new definition necessary
mixrampdelay			Number				State		--> new definition necessary
mount					String				String		--> io.
move					String				String		--> io.
moveid					String				String		--> io.
mute					Logical				Logical		--> io.
name					String				State		--> new definition necessary
next					Logical				Logical		--> io.
nextsong				Number				State		--> new definition necessary
nextsongid				Number				State		--> new definition necessary
outputs					String				String		--> io.
pause					Logical				Logical		--> io.
performer				String				State		--> new definition necessary	
play					Logical				Logical		--> io.
playid					Number				Integer		--> io.
playlist				Integer				String		--> io.
playlist_list			String				String		--> io.
playlistadd				String				String		--> io.
playlistclear			String				String		--> io.
playlistdelete			String				String		--> io.
playlistfind			String				String		--> io.
playlistid				Number				String		--> io.		
playlistinfo			String				String		--> io.
playlistlength			Integer				State		--> new definition necessary
playlistmove			String				String		--> io.
playlistsearch			String				String		--> io.
playtime				Number				State		--> new definition necessary
plchanges				String				String		--> io.
plchangesposid			String				String		--> io.		
pos						Number				Number		--> io.
previous				Logical				Logical		--> io.
prio					String				String		--> io.
prioid					String				String		--> io.
random					Logical				Logical		--> io.
rangeid					Number				String		--> io.
readcomments			String				String		--> io.
rename					String				String		--> io.
repeat					Logical				Logical		--> io.
replay_gain_mode		String				String		--> io.
replay_gain_status		String				String		--> io.
rescan					String				String		--> io.
rm						String				String		--> io.
save					String				String		--> io.
say						String				String		--> io.
search					String				String		--> io.
searchadd				String				String		--> io.
searchaddpl				String				String		--> io.
seek					String				Number		--> new definition necessary
seekcur					Number				Number		--> io.
seekid					String				Integer		--> new definition necessary
setvol					Integer				Integer		--> io.
shuffle					String				String		--> io.
single					Logical				state		--> new definition necessary
song					Number				Number		--> io.
songid:					Number				state		--> new definition necessary
songs:					Number				state		--> new definition necessary
state					String				String		--> io.
sticker_delete			String				String		--> io.
sticker_find			String				String		--> io.
sticker_get				String				String		--> io.
sticker_list			String				String		--> io.
sticker_set				String				String		--> io.
stop					Logical				Logical		--> io.
swap					String				String		--> io.
swapid					String				String		--> io.
time					String				State		--> new definition necessary
title					String				String		--> io.
toggleoutput			string				String		--> io.
track					Number or String	State		--> new definition necessary
unmount					String				String		--> io.
update					String				String		--> io.		
updating_db				Number				State		--> new definition necessary		
uptime					Number				State		--> new definition necessary
volume					Number				Number		--> io.
xfade					number				State		--> new definition necessary

**Comment by instalator** [comment]
All you need to do is remove the driver completely from the ioBroker and install it again.

**Comment by Kamikaze99** [comment]
Hello
i tried it, but i found that not all new definitions are available. It looks like that my list was not clear.
Example: 
object: composer should be String (Like my list) at the moment it is State.

`{
  "_id": "mpd.0.composer",
  "type": "state",
  "common": {
    "name": "Composer",
    "type": "state",
    "role": "media.composer"
  },
  "native": {},
  "acl": {
    "object": 1638,
    "state": 1638
  }
}`

object: songs should be Number (Like my list 2.column) at the moment it is State (see my list 3.column)
`{
  "_id": "mpd.0.songs",
  "type": "state",
  "common": {
    "name": "songs",
    "type": "state",
    "role": "media"
  },
  "native": {},
  "acl": {
    "object": 1638,
    "state": 1638
  }
}`

**Comment by instalator** [comment]
You can fix it yourself and make a Pull request
