### ISSUE TITLE
warning with js-controller 3

### ISSUE THREAD

**Issue by liv-in-sky** [instalator/ioBroker.mpd#29]
just for info: I got this

`mpd.0	2020-05-04 08:55:09.908	warn	(294) This object will not be created in future versions. Please report this to the developer.
mpd.0	2020-05-04 08:55:09.908	warn	(294) Object mpd.0.updating_db is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
mpd.0	2020-05-04 08:55:09.864	warn	(294) This object will not be created in future versions. Please report this to the developer.
mpd.0	2020-05-04 08:55:09.864	warn	(294) Object mpd.0.error is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
mpd.0	2020-05-04 08:55:09.822	warn	(294) This object will not be created in future versions. Please report this to the developer.
mpd.0	2020-05-04 08:55:09.821	warn	(294) Object mpd.0.name is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
mpd.0	2020-05-04 08:55:09.777	warn	(294) This object will not be created in future versions. Please report this to the developer.
mpd.0	2020-05-04 08:55:09.777	warn	(294) Object mpd.0.db_update is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json`

**Comment by instalator** [comment]
fixed https://github.com/instalator/ioBroker.mpd/commit/b4a3fd1d98a17b822600abefe5a0961a2714aed9
