### ISSUE TITLE
Config cannot be changed

### ISSUE THREAD

**Issue by sja** [instalator/ioBroker.mpd#3]
The hostname of my mpd changed. But after changing the adapter instance config, the adapter still tries to connect to the old hostname.

        mpd.0	2017-01-20 08:49:44.621	error	mpd.0 MPD Error {"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"kueche.local","host":"kueche.local","port":"6600"}

The old hostname is "kueche", the old is "kueche.local".

The strange thing is, that the form has the new value stored. After re-open, the new one is prefilled with the new value. But the log indicates login attemps to the old one. (See above log line)

**Comment by instalator** [comment]
0.2.3 version is good?
