### ISSUE TITLE
[wishlist] update value of "pause"

### ISSUE THREAD

**Issue by Locke** [instalator/ioBroker.mpd#4]
When I pause or resume mpd from another application (Cantata or MPD Remote) the value of "pause" is not updated. It would be nice when the value could be updated, as I use "pause" in vis for a button.

I guess this affects not only "pause" but also other objects, I haven't looked into it.

**Comment by instalator** [comment]
Use object - state

**Comment by Locke** [comment]
The object "state" is readonly, and I want to have an button in vis to
pause / unpause.

Am 08.02.2017 12:10 schrieb "Vladimir Vilisov" <notifications@github.com>:

**Comment by instalator** [comment]
This is done for all media adapters in IoBroker, see [table ](http://www.iobroker.net/?page_id=6489&lang=ru#i-5)below.

**Comment by Locke** [comment]
Oh, I didn't notice the ioBroker.vis-players plug-in and tried to build something on my own. I'll try that out.
